project/CRM/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Index.as_view(), name='index'),

    path('personal-account', views.AccountView.as_view(), name='personal-account'),
    path('messages', views.MessageView.as_view(), name='messages'),


    path('companies-by-name-u/', views.CompanyListNUView.as_view(), name='companies-nu'),
    path('companies-by-name-r/', views.CompanyListNRView.as_view(), name='companies-nr'),
    path('companies-by-date-u/', views.CompanyListDUView.as_view(), name='companies-du'),
    path('companies-by-date-r/', views.CompanyListDRView.as_view(), name='companies-dr'),
    path('company/<int:pk>', views.CompanyDetailView.as_view(), name='company-detail'),

    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project-detail'),

    path('add-company/', views.add_company, name='add-company'),
    path('add-project/', views.add_project, name='add-project'),
    path('add-message/', views.add_message, name='add-message'),
    path('add-address/', views.add_address, name='add-address'),
    path('add-keyword/', views.add_keyword, name='add-keyword'),
    path('add-phone/', views.add_phone, name='add-phone'),
    path('add-email/', views.add_email, name='add-email'),
]

project/project/urls.py
"""

    project URL Configuration

"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
     path('CRM/', include('CRM.urls')),
     path('', RedirectView.as_view(url='/CRM/', permanent=True)),
     path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/CRM/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Project(models.Model):
    """ Model describing the project """

    name = models.CharField(max_length=30, default='None')
    description = models.TextField(max_length=250, null=True)
    started = models.DateTimeField(auto_now_add=True)
    is_finished = models.BooleanField(default=False)
    finished = models.DateTimeField(auto_now=True)
    price = models.FloatField()
    company = models.ForeignKey('Company', on_delete=models.CASCADE, verbose_name='company')

    class Meta:
        ordering = ["-started"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('model-detail-view', args=[str(self.pk)])


class Company(models.Model):
    """ Model describing the company """

    title = models.CharField(max_length=30, default='None')
    description = models.TextField(max_length=500, null=True)
    CEO = models.CharField(max_length=30, default='Not Defined')
    creation_date = models.DateField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Companies'

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return "/company/%i/" % self.pk


class Message(models.Model):
    """ Model describing the message """

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='author')
    text = models.TextField()
    project = models.ForeignKey('Project', on_delete=models.CASCADE, verbose_name='project')

    TYPE = (
        ('a', 'application'),
        ('m', 'mail'),
        ('s', 'site'),
        ('i', 'initiative'),
    )

    interaction_type = models.CharField(max_length=1, choices=TYPE)

    VALUE = (
        ('l', 'like'),
        ('d', 'dislike'),
    )

    mark = models.CharField(max_length=1, choices=VALUE)

    def __str__(self):
        return self.text


class Address(models.Model):
    """ Model describing the address """
    address = models.CharField(max_length=100, null=True)
    company = models.ForeignKey('Company', on_delete=models.CASCADE, verbose_name='address')

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.address


class Phone(models.Model):
    """ Model describing the phone """
    phone = models.CharField(max_length=13, null=True)
    company = models.ForeignKey('Company', on_delete=models.CASCADE, verbose_name='phone')

    def __str__(self):
        return self.phone


class Email(models.Model):
    """ Model describing the e-mail """
    email = models.EmailField()
    company = models.ForeignKey('Company', on_delete=models.CASCADE, verbose_name='email')

    def __str__(self):
        return self.email


class Keyword(models.Model):
    name = models.CharField(max_length=20, default="keyword")


class UserPhoto(models.Model):
    photo = models.FileField(upload_to='CRM/photos/')
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='user')

project/CRM/forms.py
from django import forms
from .models import Company, Project, Address, Phone, Email, Message
from django.contrib.auth.models import User


class CompanyForm(forms.Form):
    title = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"class": "form-control"}))
    CEO = forms.CharField(max_length=30, label='CEO', widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows": 5}))
    address = forms.ModelChoiceField(Address.objects.all(), empty_label='str. 00-00 City Country',
                                     widget=forms.Select(attrs={"class": "form-control"}))
    phone = forms.ModelChoiceField(Phone.objects.all(), empty_label='+380(--) --- -- --',
                                   widget=forms.Select(attrs={"class": "form-control"}))
    email = forms.ModelChoiceField(Email.objects.all(), empty_label='my_mail@mail.com',
                                   widget=forms.Select(attrs={"class": "form-control"}))


class ProjectForm(forms.Form):
    name = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"class": "form-control"}))
    description = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows": 5}))
    price = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))
    company = forms.ModelChoiceField(Company.objects.all(), empty_label='Company',
                                     widget=forms.Select(attrs={"class": "form-control"}))


class AddressForm(forms.Form):
    address = forms.CharField(max_length=30, widget=forms.TextInput(attrs={"class": "form-control"}))
    company = forms.ModelChoiceField(Company.objects.all(), empty_label='Company',
                                     widget=forms.Select(attrs={"class": "form-control"}))


class PhoneForm(forms.Form):
    phone = forms.CharField(max_length=13, widget=forms.TextInput(attrs={"class": "form-control"}))
    company = forms.ModelChoiceField(Company.objects.all(), empty_label='Company',
                                     widget=forms.Select(attrs={"class": "form-control"}))


class EmailForm(forms.Form):
    email = forms.CharField(max_length=25, widget=forms.TextInput(attrs={"class": "form-control"}))
    company = forms.ModelChoiceField(Company.objects.all(), empty_label='Company',
                                     widget=forms.Select(attrs={"class": "form-control"}))


class MessageForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows": 3}))
    interaction_type = forms.ChoiceField(choices=Message.TYPE, widget=forms.Select(attrs={"class": "form-control"}))
    mark = forms.ChoiceField(choices=Message.VALUE, widget=forms.Select(attrs={"class": "form-control"}))
    project = forms.ModelChoiceField(Project.objects.all(), empty_label='Project',
                                     widget=forms.Select(attrs={"class": "form-control"}))
    author = 0


class KeywordForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))

project/CRM/views.py
from django.forms import ModelForm
from .models import Company, Project, Address, Phone, Email, Message, UserPhoto, Keyword
from django.shortcuts import render, redirect
from django.views import generic
from django.http import Http404
from .forms import CompanyForm, ProjectForm, AddressForm, PhoneForm, EmailForm, MessageForm, KeywordForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


class Index(generic.TemplateView):
    template_name = 'index.html'


class AccountView(generic.TemplateView):
    model = User
    template_name = 'CRM/personal-account.html'


class MessageView(generic.ListView):
    model = Message
    template_name = 'CRM/messages.html'
    paginate_by = 6

    def get_queryset(self):
        return Message.objects.all()

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['Messages'] = self.get_queryset()
        return context


""" Views describing company """


class CompanyListNUView(generic.ListView):
    model = Company
    template_name = "CRM/companies_by_name_u.html"
    paginate_by = 10
    ordering = "title"

    def get_queryset(self):
        return Company.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CompanyListNUView, self).get_context_data(**kwargs)
        context['Companies_Title_Upright'] = self.object_list.order_by('title')
        return context


class CompanyListNRView(generic.ListView):
    model = Company
    template_name = "CRM/companies_by_name_r.html"
    paginate_by = 10
    ordering = "-title"

    def get_queryset(self):
        return Company.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CompanyListNRView, self).get_context_data(**kwargs)
        context['Companies_Title_Reversed'] = self.object_list.order_by('-title')
        return context


class CompanyListDUView(generic.ListView):
    model = Company
    template_name = "CRM/companies_by_date_u.html"
    paginate_by = 10
    ordering = "creation_date"

    def get_queryset(self):
        return Company.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CompanyListDUView, self).get_context_data(**kwargs)
        context['Companies_Date_Upright'] = self.object_list.order_by('creation_date')
        return context


class CompanyListDRView(generic.ListView):
    model = Company
    template_name = "CRM/companies_by_date_r.html"
    paginate_by = 10
    ordering = "-creation_date"

    def get_queryset(self):
        return Company.objects.all()

    def get_context_data(self, **kwargs):
        context = super(CompanyListDRView, self).get_context_data(**kwargs)
        context['Companies_Date_Reversed'] = self.object_list.order_by('-creation_date')
        return context


class CompanyDetailView(generic.DetailView):
    model = Company

    def company_detail_view(request, primary_key):
        try:
            company = Company.objects.get(pk=primary_key)
            address = company.address_set.all()
        except Company.DoesNotExist:
            raise Http404('Company does not exist')

        return render(request, 'CRM/company_detail.html',
                      context={'company': company,
                               'address': address})


def add_company(request):
    if request.method == 'POST':
        form = CompanyForm(request.POST)
        if form.is_valid():
            Company.objects.create(**form.cleaned_data)
            return redirect('companies-du')
    else:
        form = CompanyForm()
    return render(request, 'CRM/add_company.html', context={'form': form})


""" Views describing project """


class ProjectListView(generic.ListView):
    model = Project
    paginate_by = 3

    def get_queryset(self):
        return Project.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['Projects'] = self.get_queryset()
        return context


class ProjectDetailView(generic.DetailView):
    model = Project

    def project_detail_view(request, primary_key):
        try:
            project = Project.objects.get(pk=primary_key)
        except Project.DoesNotExist:
            raise Http404('Project does not exist')

        return render(request, 'CRM/project_detail.html', context={'project': project})


def add_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            Project.objects.create(**form.cleaned_data)
            return redirect('projects')
    else:
        form = ProjectForm()
    return render(request, 'CRM/add_project.html', context={'form': form})


def add_address(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            Address.objects.create(**form.cleaned_data)
            return redirect('companies-du')
    else:
        form = AddressForm()
    return render(request, 'CRM/add_address.html', context={'form': form})


def add_phone(request):
    if request.method == 'POST':
        form = PhoneForm(request.POST)
        if form.is_valid():
            Phone.objects.create(**form.cleaned_data)
            return redirect('companies-du')
    else:
        form = PhoneForm()
    return render(request, 'CRM/add_phone.html', context={'form': form})


def add_email(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            Email.objects.create(**form.cleaned_data)
            return redirect('companies-du')
    else:
        form = EmailForm()
    return render(request, 'CRM/add_email.html', context={'form': form})


def add_message(request):
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            author = request.user
            Message.objects.create(author=author, **form.cleaned_data)
            return redirect('messages')
    else:
        form = MessageForm()
    return render(request, 'CRM/add_message.html', context={'form': form})


def add_keyword(request):
    if request.method == 'POST':
        form = KeywordForm(request.POST)
        if form.is_valid():
            Keyword.objects.create(name=form.cleaned_data['name'])
            return redirect('messages')
    else:
        form = KeywordForm()
    return render(request, 'CRM/add_keyword.html', context={'form': form})

project/CRM/templates/CRM/add_company.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-right:900px;margin-left:60px" class="form-group">
  <form action="" method="post">
    {% csrf_token %}

    {{ form.none_field.errors }}
    <div class="mb-3">
      <label for="{{ form.title.id_for_label }}" class="form-label">Title</label>
      {{ form.title }}
    </div>

    <div class="mb-3">
      <label for="{{ form.CEO.id_for_label }}" class="form-label">CEO</label>
      {{ form.CEO }}
    </div>

    <div>
      <label for="{{ form.description.id_for_label }}" class="form-label">Description</label>
      {{ form.description }}
    </div>

    <div>
      <label for="{{ form.address.id_for_label }}" class="form-label" style="margin-top:20px">Address : </label>
      {{ form.address }}
    </div>

    <div>
      <label for="{{ form.phone.id_for_label }}" class="form-label" style="margin-top:20px">Phone : </label>
      {{ form.phone }}
    </div>

    <div>
      <label for="{{ form.email.id_for_label }}" class="form-label" style="margin-top:20px">E-mail : </label>
      {{ form.email }}
    </div>

      <button style="margin-top:20px" type="submit" class="btn btn-primary">Submit</button>

  </form>
</div>
{% endblock %}

project/CRM/templates/CRM/add_email.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-right:900px;margin-left:60px" class="form-group">
  <form action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

      <button style="margin-top:20px" type="submit" class="btn btn-primary">Submit</button>

  </form>
</div>
{% endblock %}

project/CRM/templates/CRM/add_keyword.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-right:900px;margin-left:60px" class="form-group">
  <form action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

      <button style="margin-top:20px" type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

project/CRM/templates/CRM/add_message.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-right:900px;margin-left:60px" class="form-group">
  <form action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

      <button style="margin-top:20px" type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

project/CRM/templates/CRM/add_project.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-right:900px;margin-left:60px" class="form-group">
  <form action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

      <button style="margin-top:20px" type="submit" class="btn btn-primary">Submit</button>

  </form>
</div>
{% endblock %}

project/CRM/templates/CRM/companies_by_date_u.html
{% extends "base_generic.html" %}

{% block content %}
<div>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-nu' %}">Title ↓</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-nr' %}">Title ↑</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'companies-du' %}">Date ↓</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-dr' %}">Date ↑</a>
  </li>
</ul>
</div>

<div class="container">
    {% for company in Companies_Date_Upright %}
        <div class="card" style="width: 60rem;margin-top:20px">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'company-detail' company.pk %}">{{ company.title }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ company.CEO }}</h6>
                <p class="card-text">{{ company.description }}</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

project/CRM/templates/CRM/companies_by_name_r.html
{% extends "base_generic.html" %}

{% block content %}
<div>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-nu' %}">Title ↓</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'companies-nr' %}">Title ↑</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-du' %}">Date ↓</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-dr' %}">Date ↑</a>
  </li>
</ul>
</div>

<div class="container">
    {% for company in Companies_Title_Reversed %}
        <div class="card" style="width: 60rem;margin-top:20px">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'company-detail' company.pk %}">{{ company.title }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ company.CEO }}</h6>
                <p class="card-text">{{ company.description }}</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

project/CRM/templates/CRM/companies_by_name_u.html
{% extends "base_generic.html" %}

{% block content %}
<div>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="{% url 'companies-nu' %}">Title ↓</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-nr' %}">Title ↑</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-du' %}">Date ↓</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'companies-dr' %}">Date ↑</a>
  </li>
</ul>
</div>

<div class="container">
    {% for company in Companies_Title_Upright %}
        <div class="card" style="width: 60rem;margin-top:20px">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'company-detail' company.pk %}">{{ company.title }}</a></h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ company.CEO }}</h6>
                <p class="card-text">{{ company.description }}</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

project/CRM/templates/CRM/company_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}

<div class="container" style="margin-left:20px">
  <div class="card" style="width: 60rem;margin-top:20px">
    <div class="card-body">
        <h1 class="card-title">{{ company.title }}</h1>
        <p><strong>CEO:</strong>{{ company.CEO }}</p>
        <p><strong>Address:</strong></p>

        {% for address in company.address_set.all %}
            <p>{{address.address}}</p>
        {% endfor %}
        <p><strong>Phone:</strong> </p>
        {% for phone in company.phone_set.all %}
            <p>{{phone.phone}}</p>
        {% endfor %}
        <p><strong>E-mail:</strong> </p>
         {% for email in company.email_set.all %}
            <p>{{email.email}}</p>
         {% endfor %}
        <p><strong>Description:</strong> </p>
        <p>{{ company.description }}</p>
    </div>
  </div>
</div>


<div class="container" style="margin-left:20px;margin-top:20px">
    <h3>Projects : </h3>
    {% for project in company.project_set.all %}
        <div class="card" style="width: 60rem;margin-top:20px">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'project-detail' project.pk %}">{{project.name}}</a></h5>
            </div>
        </div>
    {% endfor %}
</div>

{% endif %}
{% endblock %}

project/CRM/templates/CRM/edit_project.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

project/CRM/templates/CRM/messages.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}

<div class="container">
{% for message in Messages %}
    <div class="card" style="width: 60rem;margin-top:20px">
        <div class="card-body">
            <p><strong>{{ message.author }}</strong></p>
            <p>{{ message.text }}</p>
            <p>{{ message.interaction_type }} {{ message.mark }}</p>
        </div>
    </div>
{% endfor %}
</div>
{% endif %}
{% endblock %}

project/CRM/templates/CRM/personal-account.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}

<div>
    <div class="container-fluid">
        <h1>{{ user.username }}</h1>
        <img src="photos/Melchior.png" alt="user photo">
    </div>

    <div class="container-fluid">
        <p><a href="{% url 'add-company' %}">Add Company</a></p>
        <p><a href="{% url 'add-project' %}">Add Project</a></p>
        <p><a href="{% url 'add-message' %}">Add Message</a></p>
        <p><a href="{% url 'add-address' %}">Add Address</a></p>
        <p><a href="{% url 'add-phone' %}">Add Phone</a></p>
        <p><a href="{% url 'add-email' %}">Add E-mail</a></p>
        <p><a href="{% url 'add-keyword' %}">Add Keyword</a></p>
    </div>
</div>

{% endif %}

<div class="container" style="margin-left:20px;margin-top:20px">
    <h3>Messages : </h3>
    {% for message in user.message_set.all %}
        <div class="card" style="width: 60rem;margin-top:20px">
            <div class="card-body">
                <p class="card-title">{{ message.text }}</p>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

project/CRM/templates/CRM/project_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% if user.is_authenticated %}

<div class="container" style="margin-left:20px">
  <div class="card" style="width: 60rem;margin-top:20px">
    <div class="card-body">
        <h2>{{project.name}}</h2>
        <p><a href="{% url 'company-detail' project.company.pk %}">{{ project.company.title }}</a></p>
        <p>{{ project.description }}</p>
        <p>{{ project.published }}</p>
        <p>{{ project.price }} $</p>
            </div>
    </div>
</div>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Messages:</h4>
    {% for message in project.message_set.all %}

        <p><strong>{{message.author}}</strong></p>
        <p>{{message.text}}</p>
      {% endfor %}
  </div>

{% endif %}
{% endblock %}

project/CRM/templates/CRM/project_list.html
{% extends "base_generic.html" %}

{% block content %}
  {% if Projects %}
      <div class="container">
      {% for project in Projects %}
        <div class="card" style="width: 60rem;margin-top:20px">
            <div class="card-body">
                {% if user.is_authenticated %}
                    <p><a href="{% url 'project-detail' project.pk %}">{{project.name}}</a></p>
                    <p><a href="{% url 'company-detail' project.company.pk %}">{{ project.company.title }}</a></p>
                {% else %}
                    <p>{{project.name}}</p>
                    <p>{{ project.company.title }}</p>
                {% endif %}
                <p>{{project.description}}</p>
                <p>{{project.published}}</p>
            </div>
        </div>
      {% endfor %}
      </div>
  {% else %}
      <p>There are no projects here now</p>
  {% endif %}

{% endblock %}